config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'

  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :products do
    resources :reviews
     member do
       post :add_to_cart
     end
     collection do
      get :search
    end
   end

  resources :carts do
     collection do
       delete :clean
       post :checkout
     end
   end

  resources :cart_items

     resources :orders do
     member do
       post :pay_with_alipay
       post :pay_with_wechat
       post :apply_to_cancel
     end
   end

  namespace :account do
    resources :orders
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/cart.rb
class Cart < ApplicationRecord
   has_many :cart_items
   has_many :products, through: :cart_items, source: :product

   def add_product_to_cart(product)
     ci = cart_items.build
     ci.product = product
     ci.quantity = 1
     ci.save
   end

   def total_price
     sum = 0
     cart_items.each do |cart_item|
       if cart_item.product.price.present?
         sum   += cart_item.quantity * cart_item.product.price
       end
     end
     sum
   end

   def clean!
     cart_items.destroy_all
   end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
     belongs_to :cart
   belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/goodsdetail.rb
class Goodsdetail < ApplicationRecord
  mount_uploader :avatar,AvatarUploader
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :generate_token
   belongs_to :user
   has_many :product_lists

   validates :billing_name, presence: true
   validates :billing_address, presence: true
   validates :shipping_name, presence: true
   validates :shipping_address, presence: true

   def generate_token
     self.token = SecureRandom.uuid
   end

     def set_payment_with!(method)
    self.update_columns(payment_method: method )
  end

  def pay!
    self.update_columns(is_paid: true )
  end

  include AASM

  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :shipped
    state :order_cancelled
    state :good_returned


    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid,         to: :shipping
    end

    event :deliver do
      transitions from: :shipping,     to: :shipped
    end

    event :return_good do
      transitions from: :shipped,      to: :good_returned
    end

    event :cancel_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :avatar,AvatarUploader
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :photos
  accepts_nested_attributes_for :photos
  ratyrate_rateable "speed", "engine", "price"
  has_many :goodsdetails  #产品详情图
  accepts_nested_attributes_for :goodsdetails
  has_many :reviews
  belongs_to :category
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    is_admin
  end
  has_many :orders
   ratyrate_rater
   has_many :reviews
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :admin_required


  def index
    @products = Product.all
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def update
    @product = Product.find(params[:id])
    @product.category_id = params[:category_id]

    if params[:photos] != nil
       @product.photos.destroy_all #need to destroy old pics first
       params[:photos]['avatar'].each do |a|
         @picture = @product.photos.create(:avatar => a)
       end
    end

    if params[:goodsdetails] != nil
       @product.goodsdetails.destroy_all #need to destroy old pics first
       params[:goodsdetails]['avatar'].each do |a|
        @picdetail = @product.goodsdetails.create(:avatar => a)
        end
      end


     if @product.update(product_params)
       redirect_to admin_products_path
     else
       render :edit
     end
  end



  def new
     @product = Product.new
     @photo = @product.photos.build # for create multi-photos
     @categories = Category.all.map { |c| [c.name, c.id] } # 填写分类
  end

   def create
     @product = Product.new(product_params)
     @product.category_id = params[:category_id]

     if @product.save
       if params[:photos] != nil
             params[:photos]['avatar'].each do |a|
             @photo = @product.photos.create(:avatar => a)
         end
       end

       if params[:goodsdetails] != nil
             params[:goodsdetails]['avatar'].each do |a|
             @goodsdetail = @product.goodsdetails.create(:avatar => a)
         end
       end

       redirect_to admin_products_path
     else
       render :new
     end
   end

   def destroy
     @product = Product.find(params[:id])
     @product.destroy
     redirect_to admin_products_path
   end

   private

   def product_params
     params.require(:product).permit(:title, :description, :quantity, :price, :image,:decprice,:category_id)
   end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :validate_search_key, only: [:search]
    def index
      @products = Product.all
    end

    def show
      @product = Product.find(params[:id])
      @photos = @product.photos.all
      @goodsdetails = @product.goodsdetails.all
    end

    def add_to_cart
      @product = Product.find(params[:id])
       if !current_cart.products.include?(@product)
         current_cart.add_product_to_cart(@product)
         flash[:notice] = "你已成功将 #{@product.title} 加入购物车"
       else
          flash[:warning] = "你的购物车内已有此物品"
       end
      redirect_to :back
    end

    def search
    if @query_string.present?
      search_result = Product.ransack(@search_criteria).result(:distinct => true)
      @products = search_result.paginate(:page => params[:page], :per_page => 20 )
    end
  end


  protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
    @search_criteria = search_criteria(@query_string)
  end


  def search_criteria(query_string)
    { :title_cont => query_string }
  end

  private
  def product_params
    params.require(:product).permit(:title,:description,:quantity,:price,:image)
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
  
    cart.total_price
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def render_order_paid_state(order)
    if order.is_paid?
      "已付款"
    else
      "未付款"
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/products/edit.html.erb
<h2> Edit Product </h2>

<%= simple_form_for [:admin, @product] do |f| %>

  <div class="group">
    <%= f.input :title %>
  </div>

  <div class="group">
     <%= f.select :category_id, @categories %>
   </div>

  <div class="group">
    <%= f.input :description %>
  </div>

  <div class="group">
    <%= f.input :quantity %>
  </div>

  <div class="group">
    <%= f.input :price %>
  </div>

  <div class="group">
    <%= f.input :decprice %>
  </div>

  <% if @product.photos.present? %>
    <span>目前产品图</span> <br>
    <% @product.photos.each do |p|%>
      <%= image_tag p.avatar.thumb.url%>
    <% end %>
  <% end %>

  <div class="group">
    <!--#<%= f.input :image, as: :file %>-->
    <%= f.label :"产品图" %> <br>
    <%= f.file_field :avatar,:multiple => true,name: "photos[avatar][]" %>
    <br>
  </div>

  <div class="group">
    <%= f.label :"宝贝详情" %><br>
    <%= f.file_field :avatar, :multiple => true, name: "goodsdetails[avatar][]" %>
    <br>
  </div>



  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/admin/products/index.html.erb
<h2 class="text-center">Product List </h2>
<div class="pull-right" style="padding-bottom:20px;">
  <%=link_to("Add new product",new_admin_product_path,:class => "btn btn-primary btn-sm") %>
</div>

<br>
<table class="table table-bordered" >
  <thead>
    <tr>
      <th> # </th>
      <th width="220"> Product Pic </th>
      <th> Name         </th>
      <th> Price        </th>
      <th> Action       </th>
      <th> Create Date  </th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product|%>
    <tr>
      <td>
        <%= product.id %>
      </td>
      <td>
        <%= link_to product_path(product) do%>
          <% if product.photos.present? %>
            <%= image_tag(product.photos[0].avatar.thumb.url, class: "thumbnail") %>
          <% else %>
            <%= image_tag("http://placehold.it/200x200&text=NOPic",class: "thumbnail")%>
          <% end %>
        <% end %>
      </td>
      <td>
        <%= link_to(product.title,admin_product_path(product)) %>
      </td>
      <td>
        <%= product.price%>
      </td>
      <td>
        <%= link_to("Edit",edit_admin_product_path(product))%> |
        <%= link_to("Delte",admin_product_path(product),:method => :delete,:data => {:confirm => "Are you sure?"})%>
      </td>
      <td>
        <%= product.created_at%>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<h2> New Product </h2>

<%= simple_form_for [:admin, @product] do |f| %>

  <div class="group">
    <%= f.label :"产品名称" %>
    <%= f.input :title %>
  </div>

  <div class="group">
    <%= f.label :"产品分类" %>
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Category") %>
   </div>

  <div class="group">
    <%= f.label :"产品卖点描述" %>
    <%= f.input :description %>
  </div>

  <div class="group">
    <%= f.label :"库存" %>
    <%= f.input :quantity %>
  </div>

  <div class="group">
    <%= f.label :"商城价" %>
    <%= f.input :price %>
  </div>

  <div class="group">
    <%= f.label :"市场价" %>
    <%= f.input :decprice %>
  </div>

  <div class="group">
    <!--<%#= f.input :image, as: :file %> -->
    <%= f.label :"产品图" %> <br>
    <%= f.file_field :avatar,:multiple => true,name: "photos[avatar][]" %><br>
  </div>

  <div class="group">
    <!--<%#= f.input :image, as: :file %> -->
    <%= f.label :"宝贝详情" %> <br>
    <%= f.file_field :avatar,:multiple => true,name: "goodsdetails[avatar][]" %><br>
  </div>

  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/products/index.html.erb
<div class="main-content">
<div class="row">
<div class="lp-section-1">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

  <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="https://ww1.sinaimg.cn/large/006tNbRwgy1fdd5txkjlzj31hc0b5wn8.jpg" alt="taotaole">
      </div>

      <div class="item">
        <img src="https://ww1.sinaimg.cn/large/006tNbRwgy1fdd4y5rggtj31hc0b4e37.jpg" alt="taotaole">
      </div>

      <div class="item">
        <img src="https://ww1.sinaimg.cn/large/006tNbRwgy1fdd47ngouqj31hc0b4gw4.jpg" alt="taotaole">
      </div>
    </div>

  <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div> <!-- myCarousel-->


</div>
</div>
<div class="lp-section-2" style="margin-top:10px;">
  <div class="ftitle">
    <div style="display:inline-block;width:5px; height:18px;background-color:#CC8902;">

    </div>
    <div class="mtsize" style="color:#CC8902;"> 迷人天香  品位相伴</div>
    <div class="stsize" style="color:#666;">
      /大家都在买的好货
    </div>
  </div>
  <div class="row hotpdu">

    <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="text-center" style="font-size:16px;margin-top:10px;font-weight:700;margin-top:30px;"> NATURE </div>
        <div class="hotpic">
          <%= image_tag('https://ww3.sinaimg.cn/large/006tNbRwgy1fdd6i7h33mj30c806wt9b.jpg',width: "100%",height: "100%") %>
        </div>

        <%= image_tag('https://ww1.sinaimg.cn/large/006tNbRwgy1fddalsjgr1j304d00twed.jpg',width: "60%",height: "60%",class: "hotpic-pic") %>

        <div class="hotpic-hz">
          魅力之源</div>
          <div class="hotpic-p">

            <span style="margin-left:4px;margin-right:4px;"> 提取天然</span>
            <span style="margin-left:4px;color:#666;margin-right:4px;"> 取材 </span>
            <span style="margin-left:4px;margin-right:4px;"> 清幽  </span>
            <span style="margin-left:4px;margin-right:4px;"> 精品 </span>
            <span style="margin-left:4px;margin-right:4px;"> NATURE </span>
          </div>
          <div style="margin-bottom:60px;">
          <div class="hotpic-pz">
            世界香水之源「格拉斯」</div>
          <div class="hotpic-pz">
            其香味天然</div>
          </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4">

        <div class="text-center" style="font-size:16px;margin-top:10px;font-weight:700;margin-top:30px;"> GENUIE </div>
        <div class="hotpic">
          <%= image_tag('https://ww1.sinaimg.cn/large/006tNbRwgy1fdd6j2b3dcj30c806wdg4.jpg',width: "100%",height: "100%") %>
        </div>
        <%= image_tag('https://ww3.sinaimg.cn/large/006tNbRwgy1fddan7dqmnj303p00tq2s.jpg',width: "55%",height: "55%",class: "hotpic-pic") %>
        <div class="hotpic-hz">
          品位纯真</div>
          <div class="hotpic-p">

            <span style="margin-left:4px;margin-right:4px;"> 层层筛选</span>
            <span style="margin-left:4px;color:#666;margin-right:4px;"> 正品 </span>
            <span style="margin-left:4px;margin-right:4px;"> 考究  </span>
            <span style="margin-left:4px;margin-right:4px;"> 精益 </span>
            <span style="margin-left:4px;margin-right:4px;"> GENUIE </span>
          </div>
          <div style="margin-bottom:60px;">
          <div class="hotpic-pz">
            经国际调香师甄选</div>
          <div class="hotpic-pz">
            其味纯真</div>
          </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="text-center" style="font-size:16px;margin-top:10px;font-weight:700;margin-top:30px;">UNIQUE </div>
        <div class="hotpic">
          <%= image_tag('https://ww3.sinaimg.cn/large/006tNbRwgy1fdd6jfsa5aj31hc0u0k0s.jpg',width: "100%",height: "100%") %>
        </div>
        <%= image_tag('https://ww2.sinaimg.cn/large/006tNbRwgy1fddamioaz4j304000ta9x.jpg',width: "60%",height: "60%",class: "hotpic-pic") %>
        <div class="hotpic-hz">
          独具匠心</div>
          <div class="hotpic-p">

            <span style="margin-left:4px;margin-right:4px;"> 把玩设计</span>
            <span style="margin-left:4px;color:#666;margin-right:4px;"> 独特 </span>
            <span style="margin-left:4px;margin-right:4px;"> 体贴  </span>
            <span style="margin-left:4px;margin-right:4px;"> 魅惑 </span>
            <span style="margin-left:4px;margin-right:4px;">UNIQUE</span>
          </div>
          <div style="margin-bottom:60px;">
          <div class="hotpic-pz">
            每款包装独家设计</div>
          <div class="hotpic-pz">
            魅力时刻在线</div>
          </div>
    </div>
  </div>

</div>



<div class="lp-section-4" style="margin-top:10px;">
  <div class="ftitle">
    <div style="display:inline-block;width:5px; height:18px;background-color:#CC8902;">

    </div>
    <div class="mtsize" style="color:#CC8902;"> 新品推荐 </div>
    <div class="stsize" style="color:#666;">
      /香伴为您精挑细选
    </div>
  </div>

  <ul >
    <% @products.each do |product|%>

        <li class="item">
          <%= link_to product_path(product) do %>
            <% if product.photos.present? %>
              <div class="pic">
                <%= image_tag(product.photos[0].avatar.thumb.url, class: "thumbnail", size: "200x200") %>
              </div>
            <% else %>
              <div class="pic">
                <%= image_tag("http://placehold.it/200x200&text=NoPic",class: "thumbnail",size: "200x200")%>
              </div>
            <% end %>
          <% end %>
          <div class="name">
            <%= product.title %>
          </div>
          <div class="price">
            ¥ <%= product.price%>
          </div>
        </li>

    <% end %>
  </ul>
 </div>

 <div class="lp-section-7">

   <div class="bottom-content">
    限时特惠，全场购满38元，即送Dior真我香水试用装！

      <a class="btn btn-danger btn-lg" href="/users/sign_in">马上购买</a>
  </div>


 </div>
</div>
</div>

app/views/products/search.html.erb
<div class="searchsec">
  <div class="search-result">
  <br>
  <% if @products.blank? %>
    <br>
    <div class="search-info-title">搜索信息不能为空，请输入关键字搜索</div>
  <% else %>
    <div class="search-info-title"> 有关"<%= @query_string %>"的产品信息 </div>
    <div class="searchpdu">
      <ul >
        <% @products.each do |product|%>

            <li class="item">
              <%= link_to product_path(product) do %>
                <% if product.photos.present? %>
                  <div class="pic">
                    <%= image_tag(product.photos[0].avatar.thumb.url, class: "thumbnail", size: "200x200") %>
                  </div>
                <% else %>
                  <div class="pic">
                    <%= image_tag("http://placehold.it/200x200&text=NoPic",class: "thumbnail",size: "200x200")%>
                  </div>
                <% end %>
              <% end %>
              <div class="name">
                <%= product.title %>
              </div>
              <div class="price">
                ¥ <%= product.price%>
              </div>
            </li>

        <% end %>
      </ul>


      </div>
    </div>
    <div class="text-center">
      <%= will_paginate(@products, renderer: BootstrapPagination::Rails) %>
    </div>
  <% end %>
</div><!-- wdt1200-->
</div>

app/views/products/show.html.erb
<div class="goods-detail-sec secbakgrd ">
  <div class="secmid ">

    <div class="container-fluid wdt1200 ">
    	<ul class="breadcrumb">
      	<li class="note-color">您的位置：</li>
        <li><a href="/" class="fontlink;">首页</a></li>
        <li class="divider-sm">/</li>
        <li class="active"><%= @product.category.name %></li>
        <li class="divider-sm">/</li>
        <li class="active"><%= @product.title %></li>
      </ul>
    </div> <!--breadcrumb -->

    <div class="gods-detail-box">
      <div class="container-fluid wdt1200 ">
         <div class="gods-detail-pic">
          <div class="gods-main-pic">
              <% if @photos.present? %>
              <a class="magnifier-wrapper" href="#">
                <%= image_tag(@photos.first.avatar.medium.url, class: "thumbnail",size: "400x400") %>
              </a>
              <% else %>
                <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
              <% end %>
          </div>

          <ul class="goods-thumb-pic">
            <% if @photos.present? %>
              <% @photos.each_with_index do |p, index| %>
                <% if index == 0 %>
                  <li class="border intro-preview-item intro-preview-activeItem fl">
                <% else %>
                  <li class="border intro-preview-item fl">
                <% end %>
                <% if index < 5 %>
                  <%= image_tag(p.avatar.medium.url,size: "74x74") %>
                <% end %>
                  </li>
              <% end %>
            <% end %>
          </ul>
        </div><!--gods-detail-pic -->
          <div class="gods-detail-info">
            <div style="font-size:24px;"> <%= @product.title %>
            </div>
            <p class="desc" style="padding-top:10px;color: #999;">
                <%= @product.description %>
            </p>
            <div class="price-box">
              <div class="goods-params">
                 <div class="params-key">
                   售价
                 </div>
                 <div class="params-value">
                   <strong class="sale-price"> ¥<%= @product.price %></strong>
                 </div>
              </div>

              <div class="goods-params">
                 <div class="params-key">
                   市场价
                 </div>
                 <div class="params-value">
                   <del> ¥<%= @product.decprice %></del>
                 </div>
              </div>
            </div>

            <div class="goods-params">
               <div class="params-key">
                 库存
               </div>
               <div class="params-value">
                 <%= @product.quantity %>
               </div>
            </div>
            <div>


            <div class="">
              <% if @product.quantity.present? && @product.quantity > 0 %>
                <%= link_to("加入购物车", add_to_cart_product_path(@product), method: :post,
                    class: "btn btn-lg btn-primary") %>
             <% else %>
                已销售一空，无法购买
             <% end %>
           </div>
         </div> <!--gods-detaile-info -->
       </div>
    </div>
  </div><!-- gods-detail-box-->

    <div class="goodsbar j_goodsbar">
    	<div class="container wdt1200 ">
      	<div class="pull-left goods">
        	<div class="pic">
          <!--<%#= image_tag(@product.image.medium.url, size: "58x58" ) %>-->
            <%= image_tag(@product.photos[0].avatar.thumb.url, class: "thumbnail", size: "58x58") %>
          </div>
          <div class="name">
          	<div class="nav-name"><%= @product.title%></div>
            <strong>本店价：￥<%= @product.price %></strong>
          </div>
        </div>
        <h3 class="pull-left tab-nav" data-target="#J_tabContentItemDetail">
        	<a class=" item nav-item active fontlink" href="#">商品详情</a>
        	<a class=" item nav-item fontlink">买家评价（<%= @product.reviews.count %>）</a>
        </h3>
        <div class="pull-right btns">
        	                    <!--<button class="btn btn-primary" type="button">立即购买</button>-->
          <button class="btn btn-primary j_addCart" type="button" data-auto="0">
            <i class="fa fa-cart-plus"></i>
            <%= link_to("加入购物车", add_to_cart_product_path(@product), method: :post) %>

          </button>
          </div>
        </div>
    </div><!-- goodsbar -->

    <div class="container-fluid wdt1200 ">
        <div class="history-box">
          <div class="title">
            <span>看了又看</span>
          </div>

          <ul class="goods-list has-space">
            <% Product.limit(6).each do |product| %>
                  <li>
                    <%= link_to(product_path(product), class: "item")  do %>
                     <div class="pic">
                      <% if product.photos.present? %>
                        <%= image_tag(product.photos[0].avatar.thumb.url, class: "", size: "160x160") %>
                      <% else %>
                        <%= image_tag("http://placehold.it/200x200&text=No Pic") %>
                      <% end %>

                    </div>

                    <div class="name">
                     <%= @product.title%>
                    </div>
                    <div class="price">
                     ¥<%= @product.price %>
                     <span>
                     <del style="color: #999;padding-left:10px;">    ¥<%= @product.decprice %></del></span>
                    </div>
                      <% end %>
                </li>

            <% end %>

          </ul>



        </div><!-- history-box 历史产品记录-->
        <div class="detail-box">
          <div class="params-box">
            <strong>产品名称：</strong>
            <%= @product.title%>
          </div>

          <div class="shopping-box">

          </div>

          <div class="advantage-box">
            <div class="item">
              <h3> <strong> 原装正品100%</strong></h3>
              <p>
                “淘淘乐自营”
                <br>
                "海外直接采购，全程政府监管"
              </p>
            </div>

            <div class="item">
              <h3> <strong> 原装正品100%</strong></h3>
              <p>
                “淘淘乐自营”
                <br>
                "海外直接采购，全程政府监管"
              </p>
            </div>

            <div class="item">
              <h3> <strong> 原装正品100%</strong></h3>
              <p>
                “淘淘乐自营”
                <br>
                "海外直接采购，全程政府监管"
              </p>
            </div>

          </div>
          <div class="detail">
          <div class="test-item" style="display: block;">
            <div class="descr-box">
              <p>
                <% if @goodsdetails.present? %>
                  <% @goodsdetails.each_with_index do |p, index| %>
                    <%= image_tag p.avatar.medium.url %>
                  <% end %>
                <% else %>
                  <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
                <% end %>
              </p>
            </div> <!-- 产品详情页 descr-box-->
          </div>


          <div class="test-item">
            <div class="comment-box">
              <h3 class="reviews_title">
                共 <%= @product.reviews.count %> 个评价
              </h3>
            <hr>

            <div id="reivews">
              <!--<div class="">
                味道 : <%= rating_for @product, 'speed', disable_after_rate: true, star_path: '/images/ratyrate' %>
              </div> -->
              <%= render @product.reviews%>

              <%= render "reviews/form"%>


            </div>

          </div> <!-- 产品评论页comment-box-->
        </div>
      </div><!--detail -->
    </div><!--detail box-->
  </div>


  </div>
</div>