config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'

  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :products do
    resources :reviews
     member do
       post :add_to_cart
     end
     collection do
      get :search
    end
   end

  resources :carts do
     collection do
       delete :clean
       post :checkout
     end
   end

  resources :cart_items

     resources :orders do
     member do
       post :pay_with_alipay
       post :pay_with_wechat
       post :apply_to_cancel
     end
   end

  namespace :account do
    resources :orders
  end
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/cart.rb
class Cart < ApplicationRecord
   has_many :cart_items
   has_many :products, through: :cart_items, source: :product

   def add_product_to_cart(product)
     ci = cart_items.build
     ci.product = product
     ci.quantity = 1
     ci.save
   end

   def total_price
     sum = 0
     cart_items.each do |cart_item|
       if cart_item.product.price.present?
         sum   += cart_item.quantity * cart_item.product.price
       end
     end
     sum
   end

   def clean!
     cart_items.destroy_all
   end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
     belongs_to :cart
   belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/goodsdetail.rb
class Goodsdetail < ApplicationRecord
  mount_uploader :avatar,AvatarUploader
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :generate_token
   belongs_to :user
   has_many :product_lists

   validates :billing_name, presence: true
   validates :billing_address, presence: true
   validates :shipping_name, presence: true
   validates :shipping_address, presence: true

   def generate_token
     self.token = SecureRandom.uuid
   end

     def set_payment_with!(method)
    self.update_columns(payment_method: method )
  end

  def pay!
    self.update_columns(is_paid: true )
  end

  include AASM

  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :shipped
    state :order_cancelled
    state :good_returned


    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid,         to: :shipping
    end

    event :deliver do
      transitions from: :shipping,     to: :shipped
    end

    event :return_good do
      transitions from: :shipped,      to: :good_returned
    end

    event :cancel_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :avatar,AvatarUploader
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :photos
  accepts_nested_attributes_for :photos
  ratyrate_rateable "speed", "engine", "price"
  has_many :goodsdetails  #产品详情图
  accepts_nested_attributes_for :goodsdetails
  has_many :reviews
  belongs_to :category
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    is_admin
  end
  has_many :orders
   ratyrate_rater
   has_many :reviews
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
  
    cart.total_price
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def render_order_paid_state(order)
    if order.is_paid?
      "已付款"
    else
      "未付款"
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer style="margin-top: 20px;">
  <div class="lp-section-5">
   <section class="container-fluid">
    <div class="row  text-center">
      <div class="col-xs-6 col-md-3">
        <%= image_tag("https://ww1.sinaimg.cn/large/006tNc79gy1fchouk1v8lj30m80m8q39.jpg",size:"50x50")%>
        正品保障
        平台信誉 品质保证
      </div>
      <div class="col-xs-6 col-md-3">
        <%= image_tag("https://ww3.sinaimg.cn/large/006tNc79gy1fchox1n6abj305k05k0sm.jpg",size:"50x50")%>
        全球直供
        海外资源 一站选购
      </div>
      <div class="col-xs-6 col-md-3">
        <%= image_tag("https://ww4.sinaimg.cn/large/006tNc79gy1fchrbo4rm8j305k05kjrb.jpg",size:"50x50")%>
        极速物流
        闪电物流 急您所需
      </div>
      <div class="col-xs-6 col-md-3">
        <%= image_tag("https://ww1.sinaimg.cn/large/006tNc79gy1fchrdg1kkej305k05kq2s.jpg",size:"50x50")%>
        低价省时
        省时无忧 低价保障
      </div>
    </div>
  </section>
  </div>


  <!--<div class="lp-section-6">
    <section class="container">
      <div class="row">

        <div class="col-xs-4 col-md-2">
          <h6> 新手指南 </h6>
          <p>
            购物流程
            <br>
            购物须知
          </p>
        </div>
        <div class="col-xs-4 col-md-2">
          <h6> 售后服务 </h6>
          <p>
            退款／退货规则
            <br>
            退款／退货流程
          </p>
        </div>
        <div class="col-xs-4 col-md-2">
          <h6> 支付配送 </h6>
          <p>
            支付方式
            <br>
            配送方式
          </p>
        </div>
        <div class="col-xs-12 col-md-6">
          <div class="pull-right">
              <i class="icons icon-quickmark-weixin"></i>
              <h4>快乐购官方微信</h4>

            </div>
        </div>

      </div>
    </section>
  </div>  -->

  <div class="footer" id="footer">
        <div class="container-fluid ">
            <div class="row">
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3>使用帮助 </h3>
                    <ul>
                        <li> <a href="#"> 新手指南 </a> </li>
                        <li> <a href="#"> 常见问题</a> </li>
                        <li> <a href="#"> 帮助中心</a> </li>
                        <li> <a href="#"> 用户协议</a> </li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> 支付方式 </h3>
                    <ul>
                        <li> <a href="#"> 货到付款</a> </li>
                        <li> <a href="#"> 在线支付 </a> </li>
                        <li> <a href="#"> 余额支付 </a> </li>
                        <li> <a href="#"> 现金券支付 </a> </li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> 配送方式 </h3>
                    <ul>
                        <li> <a href="#"> 包邮政策 </a> </li>
                        <li> <a href="#"> 配送说明 </a> </li>
                        <li> <a href="#"> 运费说明 </a> </li>
                        <li> <a href="#"> 验货签收 </a> </li>

                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> 售后服务 </h3>
                    <ul>
                        <li> <a href="#"> 正品承诺 </a> </li>
                        <li> <a href="#"> 售后咨询 </a> </li>
                        <li> <a href="#"> 退货政策 </a> </li>
                        <li> <a href="#"> 退货办理 </a> </li>

                    </ul>
                </div>
                <div class="col-lg-3  col-md-4 col-sm-6 col-xs-12 ">
                    <h3> 联系我们 </h3>
                    <div class="contactus">

                    <!--  <%= image_tag("https://ww3.sinaimg.cn/large/006tNbRwgy1fcor83fhgrj30by0byaav.jpg")%>


                      <%= image_tag("https://ww3.sinaimg.cn/large/006tNbRwgy1fcoy0at94yj30b80a275e.jpg")%>
                    -->

                    </div>
                    <ul class="social">
                        <li> <a href="#"> <i class=" fa fa-weixin">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-qq">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-google-plus">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-facebook">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-twitter">   </i> </a> </li>
                    </ul>
                </div>
            </div>
            <!--/.row-->
        </div>
        <!--/.container-->
    </div>
    <!--/.footer-->
  <section class="text-center" >
    Copyright© 2014-2017 HappyGo HappyGo.com All Rights Reserved. 鄂ICP备14091961号-2
    <br>
    Design by echo
  </section>
</footer>

app/views/common/_navbar.html.erb
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>  -->

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid ">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Sweet Partner</a>
     </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <!--<%= link_to("Products",products_path)%>  -->

        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to carts_path do  %>
            购物车 <i class="fa fa-shopping-cart"> </i> ( <%= current_cart.products.count %> )
          <% end %>
        </li>
        <li>
         <!--  <%= link_to("登录","#")%> -->
          <li> <%= link_to("我的订单",account_orders_path)%></li>
          <% if !current_user%>
            <li><%= link_to("免费注册",new_user_registration_path) %></li>
            <li><%= link_to("请登录",new_user_session_path)%></li>
          <% else %>
            <li class="dropdown">

              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Hi!,<%= current_user.email%>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <% if current_user.admin?%>
                <li><%= link_to("管理后台",admin_products_path)%></li>
                <% end %>
                <li>
                  <%= link_to("我的订单", account_orders_path ) %>
                </li>
                <li><%= link_to("退出",destroy_user_session_path,method: :delete)%></li>
              </ul>
            </li>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <div class="logobar secmid">

   <div class="container-fluid wdt1200 ">
     <div class="pull-left">
       <a href="/">
         <img class="logo" src="https://ww3.sinaimg.cn/large/006tNbRwgy1fdd31uyvq0j308v02qdg5.jpg" alt="香伴 www.xiangban.com">
        </a>
     </div>
     <div class="pull-left">
       <a href="/" class="pull-left">
         <img class="activity" src="https://ww3.sinaimg.cn/large/006tNbRwgy1fdd2c7dgoog303c02sjt1.gif" alt="香伴 www.happygo.com">
        </a>
     </div>
     <div class="pull-right">
       <div class="acart">
        <a class="btn btn-default  btn-cart" href="/carts">
        <!--  <div class="icart">
            <i class="fa fa-shopping-cart"> </i>
          </div> -->
            我的购物车 <i class="fa fa-angle-right"></i>
            <span class="badge"><%= current_cart.products.count %></span>
        </a>
       </div>
      </div>

      <!--form test -->
      <div class="pull-right searchform">
           <%= form_tag search_products_path , :method => :get  do %>
            <div class="input-group" id="search-id" >
              <input type="text" class="form-control" name="q" value="<%= params[:q] %>" placeholder="请输入香水关键词甄选您的品位！">
              <div class="input-group-btn">
                <button class="btn btn-default" type="submit">
                  <i class="fa fa-search"></i>
                </button>
              </div>

            </div>
           <% end %>

           <div class="searchstyle" >
         <div style="color:#cc8902;font-size:12px;">热门搜索：
         </div>
         <div>
           <a href="#" class="highlight" target="_self">女神节</a>
         </div>
         <div>
           <a href="#" class="highlight" target="_self">Dior</a>
         </div>
         <div>
           <a href="#" class="highlight" target="_self">Chanel</a>
         </div>
         <div>
           <a href="#" class="highlight" target="_self">Jo Malone</a>
         </div>
         <div>
           <a href="#" class="highlight" target="_self">Estee Lauder</a>
         </div>
         <div>
           <a href="#" class="highlight" target="_self">Nina Ricci</a>
         </div>

      </div><!--searchstyle -->
        </div>
     <!--form test -->

    </div>
   </div>


</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaoTaoLe后台</title>
    <%= stylesheet_link_tag 'application',media: 'all','data-turbolinks-track' => true%>
    <%= javascript_include_tag 'application','data-turbolinks-track' => true %>
    <%= csrf_meta_tags%>

  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <div class="row">
        <div class="col-md-2">
          <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
            <li>
              <%= link_to("Products",admin_products_path) %>
            </li>
            <li>
              <%= link_to("Orders",admin_orders_path) %>
            </li>
            <li>
              <%= link_to("Orders",admin_orders_path) %>
            </li>
            <li>
              <%= link_to("Orders",admin_orders_path) %>
            </li>
          </ul>
        </div>
        <div class="col-md-10">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SweetPartner</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body >
    <div class="container-fluid">
      <div class="row">
        <%= render "common/navbar"%>
        <%= render "common/flashes"%>


      <%= yield %>
    </div>

      <div class="row">
        <%= render "common/footer"%>
      </div>

  </body>

</html>